# See this guide for more settings:
#
# http://about.travis-ci.org/docs/user/build-configuration/

language: clojure
lein: lein2
script: lein2 compile, midje
branches:
  only:
    - develop
    - master
jdk:
  - openjdk6
notifications:
  email:
    - nathanmarz@gmail.com
    - sritchie09@gmail.com

